In [ ]:
#primary function

def average_calculator(lab_file):
    import numpy as np
    import pandas as pd
    from time import strftime
    from constructor import Lab, Building
    from datetime import date, timedelta, datetime

    data = pd.read_csv(lab_file,skiprows=[0])
    #Drop NaN and 0 values
    data = data.dropna(subset=['Value'])
    data = data.loc[data["Value"]!=0]
    #lab_222 = lab_222.loc[lab_222["Value"]!=0] #check if Mahika drops her zeros
    data = data.reset_index()
    data = data.drop("index", axis = 1)
    #month average calculations
    #determining what month we want to conduct our calculations from
    current_month = strftime("%b")
    month_dict = {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4,
                 'May': 5, 'Jun':6, 'Jul': 7, 'Aug': 8,
                 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec':12}
    month_results_dict = {1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 
                          7:0, 8:0, 9:0, 10:0, 11:0, 12:0}

    month_num = month_dict[current_month]

    month_sum = 0
    month_count = 0
    month_index_list = [] #list to host indices of all relevant dates (from month) in the spreadsheet

    #month average
    for i in np.arange(0, data.shape[0]):
        day = data["Date"][i]
        #get the month in the current value of the column
        day_split = day.split('/')
        csv_month = day_split[0]
        csv_month = int(csv_month)
        if csv_month == month_num: 
            month_index_list.append(i)
            month_sum = month_sum + data['Value'][i]
            month_count = month_count + 1 
            
    month_average = month_sum/month_count
    
    #updating month_results_dict
    month_update = {month_num : month_average}
    month_results_dict.update(month_update)
    
    #week average calculations when given week dates

    #week_start_date = date(Building.week.start_date) #CHECK SYNTAX OF THIS
    #week_end_date = date(Building.week.end_date) #''''''

    week_start_date = date(2023, 5, 8)
    week_end_date = date(2023, 5, 14)

    # difference between current and previous date
    delta = timedelta(days=1)

    # store the dates between start and end dates in a list
    week_dates = []

    while week_start_date <= week_end_date:
        # add current date to list by converting  it to iso format
        week_dates.append(week_start_date.isoformat())
        # increment start date by timedelta
        week_start_date += delta

    for i in np.arange(0,len(week_dates)):
        init = week_dates[i].split("-")
        year = init.pop(0)
        init.append(year)
        s = '/'
        new_date = s.join(init)
        week_dates[i] = new_date

    date_format = "%m/%d/%Y"

    for i in np.arange(0,len(week_dates)):
        week_dates[i] = datetime.strptime(week_dates[i], date_format)

    #convert all dates in relevant columns 

    lab_subset = data[month_index_list[0]:month_index_list[len(month_index_list)-1]]
    lab_subset = lab_subset.reset_index(drop = True)

    week_sum = 0
    week_count = 0
    week_spec_dates = []
    iterations = 0

    for i in np.arange(0,lab_subset.shape[0]):
        initial_date = lab_subset["Date"][i]
        initial_date_list = initial_date.split(" ")
        date_obj = datetime.strptime(initial_date_list[0], date_format)
        for j in np.arange(0,len(week_dates)):
            if date_obj == week_dates[j]:
                week_sum = week_sum + lab_subset['Value'][i]
                week_count = week_count + 1

    week_average = week_sum/week_count

In [4]:
import numpy as np
import pandas as pd
from time import strftime
#from constructor import Lab, Building
from datetime import date, timedelta, datetime

#import raw spreadsheet, skip first row with title
lab_222 = pd.read_csv("L222 MTCO2.csv",skiprows=[0])

#Drop NaN and 0 values
lab_222 = lab_222.dropna(subset=['Value'])
#lab_222 = lab_222.fillna(0)
#lab_222 = lab_222.loc[lab_222["Value"]!=0]

lab_222 = lab_222.reset_index()
lab_222 = lab_222.drop("index", axis = 1)
lab_222

                                 Date   Excel Time     Value Notes
0      10/26/2022 10:34:00.070 AM EDT  44860.44028  0.000000   NaN
1          10/26/2022 10:40:00 AM EDT  44860.44444  0.000000   NaN
2          10/26/2022 10:50:00 AM EDT  44860.45139  4.947352   NaN
3          10/26/2022 11:00:00 AM EDT  44860.45833  5.418529   NaN
4          10/26/2022 11:10:00 AM EDT  44860.46528  5.418529   NaN
...                               ...          ...       ...   ...
31947        6/5/2023 04:10:00 PM EDT  45082.67361  7.538823   NaN
31948        6/5/2023 04:20:00 PM EDT  45082.68056  7.538823   NaN
31949        6/5/2023 04:30:00 PM EDT  45082.68750  7.538823   NaN
31950        6/5/2023 04:40:00 PM EDT  45082.69444  7.538823   NaN
31951        6/5/2023 04:50:00 PM EDT  45082.70139  7.538823   NaN

[31952 rows x 4 columns]

In [5]:
#month average calculations
#determining what month we want to conduct our calculations from
current_month = strftime("%b")
month_dict = {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4,
             'May': 5, 'Jun':6, 'Jul': 7, 'Aug': 8,
             'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec':12}

month_num = month_dict[current_month]
calc_month = month_num - 2

month_sum = 0
month_count = 0
month_index_list = [] #list to host indices of all relevant dates (from month) in the spreadsheet

#month average
for i in np.arange(0, lab_222.shape[0]):
    day = lab_222["Date"][i]
    #get the month in the current value of the column
    day_split = day.split('/')
    csv_month = day_split[0]
    csv_month = int(csv_month)
    if csv_month == 5: #normally should be month_num but we have an outdated xlsx
        month_index_list.append(i)
        month_sum = month_sum + lab_222['Value'][i]
        month_count = month_count + 1
        
        
#print(month_count)
month_average = month_sum/month_count
print("Month average: ", month_average)
#print(month_index_list)

Month average:  6.025939990772352

In [6]:
#week average calculations when given week dates
#week_dates = Building.week
#week_end_date = 


#week_start_date = date(Building.week.start_date) #CHECK SYNTAX OF THIS
#week_end_date = date(Building.week.end_date) #''''''

week_start_date = date(2023, 5, 8)
week_end_date = date(2023, 5, 14)


#week_start_date = datetime.strptime("5-29-2023", "%m-%d-%Y")
#week_end_date = datetime.strptime("6-2-2023", "%m-%d-%Y")

# difference between current and previous date
delta = timedelta(days=1)

# store the dates between start and end dates in a list
week_dates = []

while week_start_date <= week_end_date:
    # add current date to list by converting  it to iso format
    week_dates.append(week_start_date.isoformat())
    # increment start date by timedelta
    week_start_date += delta

for i in np.arange(0,len(week_dates)):
    init = week_dates[i].split("-")
    year = init.pop(0)
    init.append(year)
    s = '/'
    new_date = s.join(init)
    week_dates[i] = new_date

    
date_format = "%m/%d/%Y"

for i in np.arange(0,len(week_dates)):
    week_dates[i] = datetime.strptime(week_dates[i], date_format)




#convert all dates in relevant columns 

lab_subset = lab_222[month_index_list[0]:month_index_list[len(month_index_list)-1]]
lab_subset = lab_subset.reset_index(drop = True)
    
week_sum = 0
week_count = 0
week_spec_dates = []
iterations = 0

for i in np.arange(0,lab_subset.shape[0]):
    initial_date = lab_subset["Date"][i]
    initial_date_list = initial_date.split(" ")
    date_obj = datetime.strptime(initial_date_list[0], date_format)
    for j in np.arange(0,len(week_dates)):
        if date_obj == week_dates[j]:
            week_sum = week_sum + lab_subset['Value'][i]
            week_count = week_count + 1

week_average = week_sum/week_count
print("Week average: ", week_average)
print("Week count: ", week_count)

Week average:  5.859321658432561
Week count:  1008